### ISSUE TITLE
Ideas on defining register class symbols in `std::arch` module for inline assembly

### ISSUE THREAD

**Issue by luojia65** [rust-lang/project-inline-asm#1]
https://internals.rust-lang.org/t/pre-rfc-2-inline-assembly/11310/147?u=luojia

**Comment by joshtriplett** [comment]
I agree with the response at https://internals.rust-lang.org/t/pre-rfc-2-inline-assembly/11310/150 . I don't think we can define arbitrary register classes, and I don't think we should define the built-in register classes as symbols.

**Comment by luojia65** [comment]
As for now it's not possible as the dependencies the `rustc` relies on does not support this feature. Close by now, if there could be advancements in the future, this issue may be reopened.
