### ISSUE TITLE
in(eax) + lateout(eax) vs inlateout(eax)

### ISSUE THREAD

**Issue by amosonn** [rust-lang/project-inline-asm#12]
Is there any difference between specifying `in("eax") <in_expr>, lateout("eax") <out_expr>` and `inlateout("eax") <in_expr> => <out_expr>`? If there isn't, one of them should probably be an error, or at least a warning ("one way to do each thing").

**Comment by Amanieu** [comment]
There is indeed no difference, the two are equivalent.

**Comment by amosonn** [comment]
Well, I would at least note this in the RFC, but preferably make this an error, just like `in("eax") + out("eax")` already is. I'll add this comment on the main thread of the RFC as well. Thanks!
