### ISSUE TITLE
`k` template modifier in x86

### ISSUE THREAD

**Issue by amosonn** [rust-lang/project-inline-asm#13]
I don't know if this is the place for such comments, but:
What is the reason for using `k` as the modifier for getting the 32-bit version of the register (i.e. `eax`), instead of the common `d` (for `dword`)? This matches using `w` for the `word` and `q` for the `qword` versions.

**Comment by Amanieu** [comment]
The latest version of the RFC is at https://github.com/rust-lang/rfcs/pull/2850. The one in this repo is out of date. I have changed the modifiers to make them more consistent in the updated RFC.

**Comment by amosonn** [comment]
Cool, thanks!
