### ISSUE TITLE
Tied operands with different size

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/project-inline-asm#9]
In https://immunant.com/blog/2020/01/quake3/ it was noted at the "Tied Operands in Inline Assembly" section that gcc and clang use the biggest of the operands as register size and then truncates when necessary. LLVM however leaves this undefined.

**Comment by Amanieu** [comment]
This is already covered in the draft RFC:

> If an `inout` is used where the output type is smaller than the input type then some special handling is needed to avoid LLVM issues. See [this bug][issue-65452].

[issue-65452]: https://github.com/rust-lang/rust/issues/65452
